### PR TITLE
Put in place code to run Doxygen...

### PR DESCRIPTION
**Pull request by rocky**

### CODE REVIEW

**Review by boretom — COMMENTED** [review]
How do I get the Doxygen files generated? Is there a `make` target? Running `run_doxygen` manually work well.

**Comment by rocky** [comment]
> How do I get the Doxygen files generated? Is there a make target? Running run_doxygen manually  work well.

FIrst, you need to rebuild `configure` so that when it is run it creates `doc/doxygen/Makefile`.  There is probably some Make or automake magic that might automate this better. Dunno. 

Then yes, run `doc/doxygen/run_doxygen` and that should rebuild everything.

~And that too should be hooked in the the top-level.~

And while on this topic when I look at the list of [files](http://bashdb.sourceforge.net/remake/doxygen/files.html) produced I see that all of the debugger commands should include a line describing each. E.g. see the empty line for `command/break.h`

In are [comments in that file](https://github.com/rocky/remake/blob/remake-4-3/src/debugger/command/break.h#L2-L3), I just forgot to add the doxygen formatting.

And that brings up a potential merge conflict between the two existing PRs. 

Of course I'd like to add the doxygen formatting, but also the file should be renamed to `src/debugger/command/break.c` which would be in the features/libebugger branch. 

Suggestions for how to proceed?  One possibility is to merge both of these branches, then rebase each so each gets the other, and then proceed.  If you are not planning on the rename soon, I could probably slip the commenting in before. If you are in the middle of this or going to be doing soon, I can wait.

**Comment by rocky** [comment]
881107d adds hooking the Doxygen build into the top level.

**Comment by boretom** [comment]
>If you are not planning on the rename soon, I could probably slip the commenting in before.

Go on, I'll deal with the merge conflicts when it shows up. My mind is not free to work well, I'm stuck here on the island and don't get off it that easy.

**Comment by boretom** [comment]
I may be done today or in a week, depends on my mood a bit right now, Sorry about that.

**Comment by rocky** [comment]
> here on the island

Which Island? Not the same one I live on. 

I'm going to merge both in, then rebase this branch and then continue. 

When you have time and if you are so disposed you could rebase the libdebugger branch.

**Comment by boretom** [comment]
> Which Island? Not the same one I live on.

I'm on one of the Canary Island, not sure which is your :)

**Comment by rocky** [comment]
It is a smallish one off the eastern coast of the U.S.A that the [Carnarsee Indians]( https://en.wikipedia.org/wiki/Canarsee) used as a hunting ground.

**Comment by boretom** [comment]
And it got bridges to and from the island I assume. So you're not cut off hopefully. Has the Corona thingy no influence on your daily life?

**Comment by rocky** [comment]
There are bridges but they don't form an [Eulerean cycle](https://en.wikipedia.org/wiki/Seven_Bridges_of_K%C3%B6nigsberg) so you can imagine the distress that causes. 

> Has the Corona thingy no influence on your daily life?

Yes, I think it has had an impact on most of the heavily populated parts of the world by now.  I understand though that things are much worse in Germany and Europe in general (and of course China and Asia more broadly).  

When I go out in the middle of the day it is like Boston after 8PM - many shops are closed. The small businesses are the hardest hit. Restaurants can only serve food to go, and for some of the more expensive restaurants that is a big problem. But one of the order delivery services has been nice and has waived its fees for delivery. (Of course the tipping the delivery person is a good thing to do.)

A Canary Island doesn't sound like such a bad place to be stranded _if_ you have the money for the vacation.  How has this impacted you?

**Pull request merged**
