### PR TITLE
Display some debug message in color on the terminal

### PR DESCRIPTION
**Pull request by liugang**

### CODE REVIEW

**Comment by liugang** [comment]
> In debugger/cmd.c there is a separator line before the debugger input prompt. gdb doesn't do that and my other debuggers don't either. Do you think it really necessary? 

some recipes will output hundreds of lines, I have to scroll up to find where  remake<n> is. but without color and separator line, It is very hard to find the remake<n>

**Comment by liugang** [comment]
make check fail, I have fixed it
```Diff
git diff
diff --git a/remake.c b/remake.c
index d3105a1..15bbf21 100644
--- a/remake.c
+++ b/remake.c
@@ -531,9 +531,9 @@ update_file_1 (struct file *file, unsigned int depth,
   noexist = this_mtime == NONEXISTENT_MTIME;
   if (noexist) {
     if (color_option)
-      DBF (DB_BASIC, _("File `"TXTCYN"%s"TXTRST"' does not exist.\n"));
+      DBF (DB_BASIC, _("File '"TXTCYN"%s"TXTRST"' does not exist.\n"));
     else
-      DBF (DB_BASIC, _("File `%s' does not exist.\n"));
+      DBF (DB_BASIC, _("File '%s' does not exist.\n"));
     if (i_debugger_nexting && file->cmds) {
        enter_debugger(p_call_stack, file, 0, DEBUG_STEP_HIT);
     }
```

**Comment by rocky** [comment]
Please try this in your repository:

    git checkout -b highlight
    git commit 
    git push origin highlight

This is called creating a "topic branch".  

Then when issuing the pull request, make it against a branch of the same name, e.g. "highlight". 
Thanks.

then issue another pull request from the highlight branch to a highlight branch in this repository. That's called "topic" branch

**Comment by rocky** [comment]
> some recipes will output hundreds of lines,

And some output in gdb (e.g. `list 1,300`) has  hundreds of lines too. But this is just not done. What most bothers me is that you change the behavior for some instances that you find troubling. A less pervasive change and one that is more palatable, is just adding a separator on the *target* command.  But as you note, if you have a colored prompt, even that is not necessary.  In the interface I often use inside of emacs, *realgud*, it tracks prompt boundaries.

Please address the concerns and let's take after you make the request to a "highlight" branch. Thanks.

**Pull request closed without merging**
