### PR TITLE
Readthedocs and make fixes

### PR DESCRIPTION
**Pull request by rocky**
As I document the debugger I am finding bugs, simple features that should be added (like getting a list of the tasks rather than all the targets) inside the debugger, and better ways of doing things, as in showing `--tasks` output. 

It would be a pain every time this happens to create a new branch for the fix, so I've been doing it in the readthedocs branch. Sorry about that. 

I really would like to finish this stuff up and release. There is just work in the way ;-)

### CODE REVIEW

**Comment by rocky** [comment]
@boretom with respect to the recent OSX failures, I don't understand why OSX isn't finding `_history_list` which should be part of readline which is being detected.

We could had an explicit configure C compile and run test for the presense of that variable, based on the code in the failing code, but I'd rather not. 

Any idea what's up? 

googling _history_list and OSX seems to show that this kind of thing happens a bit on OSX.

**Comment by boretom** [comment]
I've seen that some time ago but didn't look closely since it's like that forever. It is simply not found in `readline/readline.h` like on Linux. `./configure` does realize that and does not set `HAVE_HISTORY_LIST`.

```bash
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking for tilde_expand() in <readline/readline.h>... no
checking for readline in -lreadline... yes
checking for history_list() in <readline/readline.h>... no
```

The `readline` package is not part of macOS and is installed using `brew`, pre-compiled.

I'll see if it can be compiled with support for history.

**Comment by rocky** [comment]
I'm confused about the data. At lInes 303-308 of https://travis-ci.org/rocky/remake/jobs/659984312
I see: 

```
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking readline/history.h usability... yes
checking readline/history.h presence... yes
checking for readline/history.h... yes
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
checking for readline in -lreadline... yes
``` 

which tells `remake` to set `HAVE_READLINE_HISTORY_H`. 
The code in `src/debugger/cmd.c` takes that to mean that there is an external `HIST_ENTRY **hist_list` defined. 

If it needs to define it itself, we can write such a test in configure by writing some C code compiling that, checking the results and setting another C preprocessor flag. 

(Again, I'd rather not do this by OS testing)

**Comment by boretom** [comment]
I just see that this is based on the problem, that `readline` is not installed by `brew`

```bash
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 93 (delta 4), reused 30 (delta 2), pack-reused 0
Receiving objects: 100% (93/93), 47.73 KiB | 3.67 MiB/s, done.
Resolving deltas: 100% (4/4), done.
Tapped (102 files, 251.5KB).
Error: Unknown command: bundle
```

That's because the osx images on Travis-CI are broken and we need to add `update: yes` to `.travis.yml`

```diff
diff --git a/.travis.yml b/.travis.yml
index f68efad4..4c962946 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,6 +5,7 @@ compiler:

 addons:
   homebrew:
+    update: yes
     packages:
       - autoconf automake gettext gcc guile lzip pkg-config readline texinfo
   apt:
```

And I see you clean-up the whole `readline` part. On branch `remake-4-3` these checks are still in and there I tried a fix. But if your's working that's even better. I give it a go later.

**Comment by rocky** [comment]
I can try adding that one line now. No harm.

**Comment by boretom** [comment]
Btw: you work as you like, with whatever method works for you.

I pushed the changes to `.travis.yml` to `upstream/readthedocs`.

**Comment by rocky** [comment]
Appearenlty,  adding update didn't do the trick. Is OSX expecting history_list to be defined in the program rather than in the library? 

If we need to make an additional [AC_RUN_IFELSE](https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Runtime.html)  check in configure, that's okay.

**Comment by rocky** [comment]
I'll hold off on this. If you would like me to write such a check I will. Otherwise I'll wait.

**Comment by boretom** [comment]
My push didn't get through, of course

**Comment by boretom** [comment]
Otherwise, what fixed it for me, additional add:

```diff
+before_script:
+  # if macOS then LDFLAGS & CPPFLAGS for readline
+  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CPPFLAGS="-I/usr/local/opt/readline/include";
+        export LDFLAGS="-L/usr/local/opt/readline/lib"; fi
```

**Comment by rocky** [comment]
Ok. I'll try that. Thanks!

**Comment by boretom** [comment]
I'm very sorry, I wasn't clear with my instructions: the `before_script` has to be a root entry, like `before_install`

**Comment by rocky** [comment]
I will be patient and wait for you to do this. No rush. Many thanks.

**Comment by boretom** [comment]
Ok, don't push anything to this branch for the next 15 minutes, ok?

**Comment by rocky** [comment]
> Ok, don't push anything to this branch for the next 15 minutes, ok?

Got it. Thanks again. Just push or force-push when you are ready.

**Comment by boretom** [comment]
Now although it compiles fine, the packages are still not installed. But everything that is needed seems to be installed per default.
I fixed that before, I'll try it on my repo and would push one additional commit. But I'll write beforehand.

**Comment by rocky** [comment]
Thanks for the information. I will be patient and wait for your direction on when it is okay to proceed.

**Comment by boretom** [comment]
@rocky, just go on. Since no additional packages seem to be necessary to compile it for macOS.

I'll check how to solve installing packages the fastest. With `update: yes` it takes forever since it updates all already installed packages. And that is not the way to go. Probably installing manually, no per plugin will be the solution. But I'll test that on my repo and let you know when it's clear how to do it.

I'm off for a few hours and look at it afterwards.

**Comment by rocky** [comment]
Ok. I'm merging this in, even though there are still some spelling and grammar mistakes in the docs, and some information that needs filling out. 

I'll continue in this branch though after the merge.

**Pull request merged**
