### PR TITLE
WIP - debugger commands, "break", "comment", "cd" and "info" in their own objects

### PR DESCRIPTION
**Pull request by rocky**
This is an example of what I was talking about with respect to creating commands in its own object file rather than having it combined as a (fat) static inside cmd.c.

### CODE REVIEW

**Comment by rocky** [comment]
@boretom Look at all of the additional stuff in commit 4fc3c13 needed to get `make distcheck` work again. 

~I think this got complex not because of changing .h to .c but in adding libdebugger.~

Yep, `make dist` is broken in `remake-4-3`. Not a big deal. Would be nice if CI testing had noticed though. 

The open question is whether this can be simplified. 

Thanks.

**Comment by boretom** [comment]
Yes, `libdebugger` needs stuff from `remake` and therefore will need references to it. It maybe can be simplified, I'll also think about it.

>Would be nice if CI testing had noticed though.

We can change the CI to run `make distcheck` instead of `make check`. I read that with Travis-CI you can specify tests that are allowed to fail. Not sure how the notification looks like but that'd be additional option.
Although I'd go with include `make distcheck` instead of `make check`.

**Comment by boretom** [comment]
Btw: `make distcheck` works fine on macOS and FreeBSD. OpenBSD not yet but let's not focus on that too much.

**Comment by rocky** [comment]
> Although I'd go with include make distcheck instead of make check.

Seems like a simple change. However, let's not do that on OSX which already takes in excess of 4 minutes, and starts *after* Ubuntu finishes. One of the things that I have done in other projects is to use a different CI service to run the other kinds of things. That way the CI kicks off more in parallel. (Yes, if we paid Travis it could do it too - this is a poor man's way to parallelize).

**Comment by rocky** [comment]
I looked at testing based on these changes so far. In the long term I think this can and will be useful, in the short term not as much for testing without a bit of work. 

In the short term then I'm thinking of using just the built-in test framework that comes with automake and extend from there. 

As in many of my other projects, the debugger portion alone as you can see has been a fair amount of work, not just to write, but to document and test.  I use it rarely, but every time I do it has been invaluable in finding and fixing problems.

**Comment by rocky** [comment]
Merging now and will continue with the rest of the commands some other time, but in this branch.

**Pull request merged**
