### PR TITLE
Feature/help show aliases

### PR DESCRIPTION
**Pull request by rocky**

### CODE REVIEW

**Review by boretom — APPROVED** [review]
Awesome work, here some points:
- you may want to change the `zshdb` references in `docs/conf.py` and `docs/features.rst`
- in `docs\Makefile` I think it would make sense to use `/usr/bin/env python3` instead of just `python` in the line starting with `SPHINXBUILD`. For me at least since my macOS still uses Python 2.7 as the default version.

`make`'s `wildcard` keyword is indeed helpful, makes it look more tidy.

**Comment by boretom** [comment]
I just saw: in the `manpage.rst` there are a lot of options missing.

**Comment by rocky** [comment]
> I just saw: in the manpage.rst there are a lot of options missing.

Are these GNU Make or `remake` options? 

`--search-parent` I'll be documenting soon

As for the `zshdb` references, I'll fix that soon too.

**Comment by boretom** [comment]
Oh, I see ... I didn't ready it your text careful enough. It's all ok, they are the `make` options.

**Comment by rocky** [comment]
@boretom I believe all of your concerns I believe are addressed in 04b38f5 . But if not, they'll be addressed in due time.  Thanks for the help. 

Lots still more to do.

**Comment by rocky** [comment]
With respect to "make" info in the remake manpage, that was too difficult to keep up to date and in sync with GNU make. 

And documenting just the remake-specific options also highlights or gives sense to how has been extended from GNU Make.

**Pull request merged**
