### PR TITLE
"make distcheck" works. Simplify.

### PR DESCRIPTION
**Pull request by rocky**
About the `#ifdef` check in main.c. 

When I remived `AM_FLAGS` this started failing. The definition is in `makeint.h`, but for some reason that must not get pulled in.  

It is not obvious to me what benefit this is for maintainer debugging, although I could probably guess. My take is that if/when this is needed by someone on the remake team we can delve more deeply. Until then, simplify. 

As for `mock.c`. I wrote that and it is intended to assist debugger testing, and I used the `die()` funciton in the profile test. I've copied `die()` out to the profile test. As for mock debugger testing, at some point I'll deal with that and probably move mock.c out of the `src` directory. For now, I just left it it untili I can get around to dealing with the bigger picture of debugger testing.

### CODE REVIEW

**Comment by rocky** [comment]
@boretom  Also, now that distcheck has a chance of working, maybe in one (not all) of the CI checks we could try a distcheck as well?

**Comment by rocky** [comment]
@boretom 

Here's my overall plan of remaining todos. Basically go over the texi documentation which invariably will probalby mean adding more to the readthedocs. 

I'm not going to attempt to start testing the debugger. 

I'm not going to try to put the debugger code in a library, just yet. If you want to try that feel fee to do so. 

If the library isn't separated this release, maybe try for next release. Also debugger testing, and probably fix debugger bugs and improve that.

**Comment by boretom** [comment]
About `make distcheck` for macOS: it fails because the tests `features/load` and `features/loadapi` won't run (`N/A`). Although these two tests will not run, the scripts create a `*.c` file each which is not deleted.

Any idea how to prevent `tests/scripts/features/{load,loadapi} from creating the source files?

```bash
rm -f Makefile
ERROR: files left in build directory after distclean:
./tests/testapi.c
./tests/testload.c
make[1]: *** [distcleancheck] Error 1
make: *** [distcheck] Error 1
```

**Comment by boretom** [comment]
And your overall plan sound ok. I wouldn't wait for the tests and library, too. I do want to look into testing a bit more and will have more time now.

**Comment by rocky** [comment]
> About make distcheck for macOS: it fails because the tests features/load and features/loadapi won't run (N/A). Although these two tests will not run, the scripts create a *.c file each which is not deleted.

I just looked into this, and this looks like a true failure on the part of building remake on OS/X.

The `features/load` file has this: 

```perl
# Don't do anything if this system doesn't support "load"
exists $FEATURES{load} or return -1;
```

so appearently, the system thought OS/X should support `load`, but it doesn't.

Had `FEATURES{load}` been set correctly, then those C files wouldn't have been created.

So now how does `FEATURES{load}` get set?

In `tests/run_make_tests.pl` there is this code to determine the feature set: 

```perl
  create_file('features.mk', 'all:;$(info $(.FEATURES))');
  %FEATURES = map { $_ => 1 } split /\s+/, `$make_path -sf features.mk`;
```

So create this Makefile: 

```make
all:
	$(info $(.FEATURES))
```
and run `./make -sf tmp/features.mk all`:

If you see `load` in the list then the OS supports `load`.

So the question now becomes, should load be disabled on OS/X. If so, how do you do that?

**Comment by boretom** [comment]
Thanks a lot, that helps. `.FEATURES` is a special `make` variable and returns a list of [make special feature](https://www.gnu.org/software/make/manual/html_node/Special-Variables.html).

You're a perl monk, no? In tests/run_make_tests.pl the result of above mentioned `make` run is stored in a map called `%FEATURES`. But that is not used anywhere afterwards. Can you maybe explain to me how `%FEATURES` is used after it is filled?

**Comment by rocky** [comment]
The `%` at the beginning of `%FEATURES` is called a "sigil" and just means that the datatype of `FEATURES` is a hash table. Perl was one of the first of the dynamic languages to provide hash tables. It was however the only one that used the `%` sigil.  Another sigil is `$` which indicates that the value is some kind of scalar value, like a number or a string. So when you see

```perl
exists $FEATURES{load} or return -1;
```
That looks up in the same `FEATURES` hash using key `load` (you don't need quotes around `load`); the value that is retrieved is a scalar value which is why there is `$` in there.

The way the `FEATURES` hash is initialized is using that `map` function which iterates over an array created by a string which is split on space boundaries. Each item split is entered into the `FEATURES` hash with value 1.

Later languages like Ruby and Python don't have sigils. 

> You're a perl monk, no?

Technically, in https://perlmonks.org my karma or rating is "scribe".

**Comment by boretom** [comment]
Now that you write it, it makes sense.

Well, on Linux and macOS the `FEATURE` map/hash is identical. But on macOS the test result is `N/A`.

**Comment by rocky** [comment]
I think this is not a Perl thing or a testing thing, but some sort of _configuration_ thing. 

First question I'd have is: does "load" work with make 4.3 on OSX? If so, I imagine there are special loader options that you have to give when you build the final `make` binary. (It's been like that often in the past. I seem to recall something with dynaloader). 

And if it is a loader flag missing, probably it is some configuration parameter that was in make 4.3 that just didn't get into remake 4.3

If on the other hand load also doesn't work on MacOSX, then there is probably something in configuration that is not detecting that this isn't available on OSX, and this configuration is missing in remake.

**Comment by rocky** [comment]
Digging deeper, I see this is tested for in `configure` and set in `config.h`:

```
/* Define to 1 to enable 'load' support in GNU make. */
#define MAKE_LOAD 1
```

In order to make this work, configure.ac says the OS needs to support `dlopen()`, `dlsym()`, and `dlerror()` which OSX is supposed to support: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/dlopen.3.html and https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/dyld.3.html#//apple_ref/doc/man/3/dyld

But I am guessing the dyld library needs to be added and isn't. 

So I am also guessing that building GNU Make 4.3 from source will have the same problem: configure will set the build to add in `.FEATURES` that `load` is avaiable, but it isn't (without some additional magic set by the builder). 

If it this does work say via `brew install`, then I am guessing those folks have added additoinal flags to configure or patched the source.

As for the test leaving around stray `.c` files, it shouldn't and that's a test writing problem in GNU Make, which it would be nice if GNU Make fixed. But for us that's a secondary problem.

**Comment by boretom** [comment]
Thanks a lot for your analysis. I ran the tests with `-verbose` and that way I got the call that is made. It runs fine on Linux but not on macOS.
The call is - not suprising - quite simple:

```bash
gcc -I<path-to-remake>/src  -g -O2 -shared -fPIC  -o testapi.so testapi.c
```

But on the macS (and FreeBSD or OpenBSD, can't remember right now) it won't find `gmk_eval` and if I add the object file that defines  it won't find the next one, and so on.

How can that work on Linux? Why doesn't one have to specify all the object files like for example `loadapi.ch` which defines `gmk_eval`?

This test fails indeed too for `make` and fixing the leftover files isn't too hard. I'll add the `unlink` command to the appropriate place, the can-we-compile `if` clause where it is missing.

**Comment by boretom** [comment]
I pushed the fix-the-leftovers-from-test to `upstream/remake-4-3`, only adding one `unlink` to `features/load` and `features/loadapi` tests.

That way `make distcheck` is successful on macOS too.

Running `make check for `make` and `remake` I realised that the first checks `features/archives` do succeed for `make` but are `N/A` with `remake`. I'll have a look at that late this afternoon.

Question about tests for the `remake` debugger: Since there are lots of testing framework, with which are you familiar the most? Python unittest? Or is using the `make` perl testing script also an option?

**Comment by rocky** [comment]
with respect to "feature/archives":  If you want to fix, go ahead, but the feature itself where members of an archive file is tested is pretty arcane. I have _never_  in my 40 or so years of working with "make" ever found a single Makefile that made use of that feature. I'd be interested to find a single example which uses this. Also, it is OS-specific because some OS's have libraries in different formats. 

I suspect it probably only a feature in GNU make. 

> Since there are lots of testing framework, with which are you familiar the most?

That's a hard question to answer. I prefer something that is simple. The problem I have with most (if not all) of behavior-driven test frameworks is that if you want to debug them you need a special tool to do it in because the "behavior wrapping" is basicaly in a different language than the one that the code is implemented in. 

Behavior driven is a kind of black-box testing where you don't get to look into the code to customize the test. But that also means that if something goes wrong, you can't report about what inside has gone wrong.  If you have contracted to write some code for someone who isn't computer savvy or doesn't want to inspect code, then BDD tests are great in order to convince the customer that you met specs, and are also great at forcing specs to be written. 

However in this case that just doesn't make a lot of sense and thus gets in the way.

As for using the Perl code, the problem is that this is a one-of-a-kind snowflake, and Perl isn't used that much anymore either. I believe it is also on maintainers list of things to redo. Part of the problem in redoing is that he has a lot of effort invested already in this framework. 

So adding more to eventually convert doesn't make a lot of sense either. 

With "mock.c" what I was working for was a way where I could write the tests in C so there is no dependency on either say Ruby and rspec (or Python with its built-in unittest), and thus debugging can be done in C (okay that's not so great), but more importantly there can be unit tests which can more precisely detect where an error is, than by running some end-to-end test. 

But in order for this to work better, it would be useful to have the debugger code available as a library. Then some scaffolding front-end code which include mock.c builds a fake "remake" for testing. Or there are a bunch of test remakes build which pull in mock.c. So this would work sort of like the way that "load.c" test works.

**Comment by boretom** [comment]
I do understand your argument and so let's not do anything big with testing until the debugger is in a library.

>with respect to "feature/archives": If you want to fix, go ahead

I put it on my todo list and see if it's just a small adjustment or more.

**Pull request merged**
