### PR TITLE
Changes from 4.3 to get 4.2.1 up to 1.5 ...

### PR DESCRIPTION
**Pull request by rocky**
This part contains only the debugger portion

-c will be next.

Not going to redo --tasks though

sphinx docs will also not be in 4.2.1 either.

### CODE REVIEW

**Review by boretom — APPROVED** [review]
`make` and `make check` works fine on macOS and FreeBSD (on FreeBSD git2cl shebang changed to /usr/bin/env perl)

**Comment by rocky** [comment]
Thanks for checking. In the next commit I'll change git2cl as you suggest.

**Comment by rocky** [comment]
@boretom Thanks for the review. With this change, and the and the ones in the remake_4_3 branch, that's aside from things that show up in testing on other platforms this is it. 

Remember to put in the datatype change from bool to in for post_mortem. 

After that one more round of checking would be great. Again, thanks.

**Comment by rocky** [comment]
Note: there will be a small change to NEWS-remake.md to add the date just before the release goes out, but I generally don't bother checking platforms after that kind of change.

**Comment by boretom** [comment]
If I do change something, on which branch should I do that? 
a) now the tests/.../dash-c and dash-C problem is back
b) shall I do the post_mortem changes?

**Comment by rocky** [comment]
Would you please fix both. You have a better handle at testing these and made the changes in the first place. So you'll do it quicker and less prone to error. 

Thanks.

**Comment by rocky** [comment]
And may apologies for the regressions.

**Comment by boretom** [comment]
Sure, I'll do that ... no worries.
I switched to Linux because of the dash-c/dash-C but now I can't find `dash-c` in the repo, neither on this branch nor on `remake-4-2`. Do you have it in your local repo?

Btw: `NEWS` will have to be edited too, otherwise `distcheck` won't be happy if that version doesn't correspond to the `remake` version.

**Comment by rocky** [comment]
> Do you have it in your local repo?

It is in git history. I deleted it since it wasn't worth the bother. 

As for distcheck on 4.2.1 I removed the need to change that as well, like we now do in the 4.3 branch.

**Comment by boretom** [comment]
Oh I see, git history read "Add dash -c remove usued OSes..." but ok then.

To what branch shall I push the changes? A new one, this one or `remake-4-2`?

**Comment by rocky** [comment]
Push to remake-4-2 -- less overhead.

**Comment by boretom** [comment]
ok, it's done. I also add the autogen.sh "MAKE aware" change. Helps me a lot on *BSD.

**Comment by rocky** [comment]
Not seeing the post-mortem bool->int change in the remake_4_3 branch yet.

**Comment by boretom** [comment]
Senior, I quote: "Push to remake-4-2 -- less overhead." :)

**Comment by rocky** [comment]
Ooops, I mean to remake-4-3 as well. 

I see some small readthedoc fixes I'll be making in remake-4-3. But would you please test on the OS's and I will be doing the same. 

Then around the 15th the final push for both releases. Thanks!

BTW I hope this hasn't been boring. In th event, based on the handle you were bored before working on this I am guessing that is that's not the situation now. I would even venture to posit that you might have learned a thing or to working on this code.

**Comment by boretom** [comment]
> Ooops, I mean to remake-4-3 as well.

Sure, I do that. I pushed it to the bug/test-script branch and will rebase or cherry-pick that commit for `remake-4-3`

> I see some small readthedoc fixes I'll be making in remake-4-3. But would you please test on the OS's and I will be doing the same.

Sure, I will do that.

Btw: `remake-4-2`: `make distcheck` works on macOS, FreeBSD.

> BTW I hope this hasn't been boring.

No no, don't worry. I quite like doing that. I especially like make it work on as many platforms as possible. Since that's what bugs me most on projects, when I try to use it and it doesn't work.

And I have learned quite some stuff, no doubt about that.

And regarding the handle: I created that some/many years ago. It's not accurate anymore but changing it doesn't sound like a good idea. My newer one would be `patient0` which is probably not the best choice right now. But that also is a few years old.
If I had a catchy first name like you, I wouldn't need one :D

**Comment by boretom** [comment]
to add: now on `remake-4-3` the `dash-c`, `dash-C` in tests is there again, got in with one of the mergers of yours. Shall I fix it again or remove `dash-c` completely in tests?

**Comment by rocky** [comment]
If you can add, great, do it. If it frustrates you like it did me it's okay to leave it. 

> I especially like make it work on as many platforms as possible. Since that's what bugs me most on projects, when I try to use it and it doesn't work.

Got it. It is helpful to understand what things you prefer to do. There's lots of work everywhere so I am more than happy to leave this to you if that's what you'd prefer to do.

**Comment by boretom** [comment]
Did you add `Enbugger` on purpose in `tests/scripts/options/dash-c`? That test fails since I don't have that module installed.

```perl
 34 use Enbugger "trepan";
 35 Enbugger->stop;
```

**Comment by boretom** [comment]
I think we have to arrange a bit better, who is doing what. You're deleting `dash-c` is interfering with what I was doing with renaming of `dash-c` and also deleting it.

What other communications tools do you use in projects? This here seems not perfect.

**Comment by rocky** [comment]
> What other communications tools do you use in projects? This here seems not perfect.

Well, there's slack and discord.

**Comment by boretom** [comment]
Ok, I'll sleep over it. I worked with Slack but discord sound good too. But maybe I just have to be more precise in letting you know what exactly I'm going to do.

Btw: pushed the post_mortem to `remake-4-3`.

**Comment by rocky** [comment]
> Btw: pushed the post_mortem to remake-4-3.

Thanks. 

> I'll sleep over it. 

Ok - whichever way you want to go is fine with me. Reducing friction is a good thing.

About the `-c` test. I was debugging what was up there earlier and was surprised it was still around.

I make a lot of mistakes like this. For things I see in testing I'll accumulate the changes in the bug/testing-tweaks branch.

**Pull request merged**
