### PR TITLE
Readthedocs

### PR DESCRIPTION
**Pull request by rocky**

### CODE REVIEW

**Review by rocky — COMMENTED** [review]
Would like to get the documentation for `--search-parent` into `remake-4-3`.

@boretom  It occurred to me after documenting this. That we could make the short option `-C`  (captal C) which which does the same as `-c` if there is no paremeter given to `-C`. 

What do you think? Are you up for making this change?

**Comment by rocky** [comment]
@boretom I've been using `-c` and a problem with substiting `-C` is that the target name would get confused as the argument to -C.  For example:

```shell
$ remake -C html
```

`html` is the target name. However this

```console
$ remake -C -- html
```
works, I think.

Given this, is it worth it?

**Comment by boretom** [comment]
@rocky how can `-c` and `-C` do the same? One is for searching parent directories for `Makefile`s and the other is for changing into a directory before running `make`.

I for sure wouldn't merge the two together. `-C` is also used in `tar` so I guess everyone expect it to behave accordingly.

**Comment by rocky** [comment]
I wasn't thinking about changing dash capital C, but _extending_ it so that when doesn't have an directory argument, the directory is implied to search from the current directory, then parent directory, up to the root. 

The current option lowercase c was selected because all the "p" and "s" single letters are already taken and it works _similar_ to the way captial C works, but just doesn't take an argument. 

But after trying this a bit, I don't thing `-C` would work because after `remake -C *target*` is a common thing to want to do, and here this would be interpreted as an argument to `-C`.

**Pull request merged**
