### PR TITLE
Add a gdb-like "load" command...

### PR DESCRIPTION
**Pull request by rocky**
This command can be used to load in a GNU Makefile from the debugger.
The short option is M for "Makefile"

### CODE REVIEW

**Comment by boretom** [comment]
I have to review it tomorrow morning, have to go to bed a bit earlier today.

**Comment by rocky** [comment]
Sleep is good! No hurry on this. The main idea was to give and example for how to add a command.

I do like this. In debug sessions I often fix the source code and the issue `load` to have the code read in, so that I can continue. 

I can also imagine having specific "debug"-oriented makefiles that aren't normally used, but when you want to trace things are avialable. I believe this is an aspect of ["aspect-oriented programming"](https://en.wikipedia.org/wiki/Aspect-oriented_programming).

**Review by boretom — APPROVED** [review]
Looks all good to me. It does compile just fine on Linux, macOS and FreeBSD.

What does `review` include btw? Testing the PR and if yes to what extend?

**Comment by rocky** [comment]
> What does review include btw? Testing the PR and if yes to what extend?

It can be anything you want it to be. Of course, I really appreciate it when you test the PR. I don't normally have access to the *BSD systems or OSX. (I am hoping CI would fill in the gaps here)

And if you are not up to review its okay to just say so.

**Pull request merged**
