### PR TITLE
Add option to look in parents for Makefile...

### PR DESCRIPTION
**Pull request by rocky**
option -c | --search-parent

See #69

I don't have a test in yet, but I'll add one in a day or so. 

I just thought this feature really cool and am already using it.

### CODE REVIEW

**Comment by boretom** [comment]
@rocky I only have time to review Wednesday or Thursday. If you can wait that long, all is good. Otherwise I'll only go through the code and accept it

**Comment by rocky** [comment]
I've been thinking about this. Here's the plan:

I am going to merge various branches into `remake-4-3`, but keep the branches around separate and continue to work off of them. Periodically, I'll rebase branches off of `remake-4-3`.

Here is what I suggest you do, but I am open for other suggestions.

When you have time, first check over `remake-4-3` for soundness. We can make additional branches or fix up existing branches in order to get `remake-4-3` more solid.

Of the remaining open branches which will be this one, `readthedocs`, and `bug/fix-make-distcheck`, look them over and work on whichever intersets you the most. 

Here is the bigger picture. I would really like to get out a release because there is a _lot_ of good stuff here. However to do full testing and full documentation is going to take a while. A bit more work than I had anticipated previously.

So I am thinking again of releasing and noting what still needs to be done so as to warn people what's up. However I think even in its current form without testing and documentation in place this is still a big improvement. 

Your thoughts?

**Comment by boretom** [comment]
The plan with the branches sound good too me, or at least I would also do it like that.

Regarding releasing: If you think it's stable enough then releasing is the way to go. Or if you're not 100% sure about the stability, release is as beta first. That way people would be aware that there may be a hick-up.

**Comment by rocky** [comment]
Right now I think this is as or more stable than the current `remake`  (a couple of debugger bugs have been fixed). 

But we can decide before release. 

What I don't want to happen is what happened with cdparanoa and vcdimager where something is called beta for decades.

**Pull request merged**
